### ISSUE TITLE
Why it is empty?

### ISSUE THREAD

**Issue by alexandre-mbm** [F123/F123PKGBuilds#1]
Why this repository do not have more files? Which is the its finality?

**Comment by ghost** [comment]
This repository would store PKGBUILDs for packages not in the official
Manjaro repositories. At this point, no PKGBUILDs are being used, so
none are here currently. Look for some to be added if needed.

**Comment by alexandre-mbm** [comment]
Does Manjaro have something as the AIR 4? I don't know.

**Comment by ghost** [comment]
If you are referring to the AUR, it is indeed available in F123. In
fact, the experimental-orca shell function gets the orca-git package
from the AUR. Yaourt is also included in the installed system, so any
package you need from the AUR can be installed easily.

**Comment by alexandre-mbm** [comment]
But F123's packages cannot be at AUR, is not? It is for Arch's packages only, is not?

**Comment by ghost** [comment]
Currently, F123 has no special PKGBUILDs. There are a few specialized
things, but they are shell scripts that are just copied into the
installed image at this time. In future, PKGBUILDs can be made, and
they can be stored in this repository. An additional binary repository
will also need to be created to hold the binary packages based on the
PKGBUILDs here.

**Comment by alexandre-mbm** [comment]
> An additional binary repository will also need to be created to hold the binary packages based on the PKGBUILDs here.

Why? One F123's AUR?

**Comment by ghost** [comment]
PKGBUILDs can be hosted in teh AUR, but in order to get built packages
onto the live image, they either need to be installable during the
build process from a binary package repository or the files need to be
copied into the profile manually. For now, F123 has had its files
copied manually, but a package repository is being investigated as an
option for the future.

**Comment by alexandre-mbm** [comment]
Git is not suitable for storing binary files.
And I have the impression of that the rules of GitHub veto such use.

**Comment by ghost** [comment]
Yes. In this case, the binary repository would probably be hosted on one 
of F123's primary servers.
